<?php

// This file was generated by running "composer dump-env dev"

return array(
    'APP_ENV' => 'dev',
    'APP_SECRET' => 'e2a3835a3f5a63c610dbdfbe071c4043',
    'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
    'DATABASE_URL' => 'mysql://laurewcmegaovh:thyCJNrtSXJRRc73GdmheJH9667f6H@laurewcmegaovh.mysql.db/laurewcmegaovh?serverVersion=8&charset=utf8mb4',
    'MAILER_DSN' => 'smtp://412e1d70c6923d:821985b74f7425@smtp.mailtrap.io:2525?encryption=tls&auth_mode=login',
    'GOOGLE_RECAPTCHA_SITE_KEY' => '',
    'GOOGLE_RECAPTCHA_SECRET' => '',
    'RECAPTCHA3_KEY' => '6LdBtpMiAAAAAKlAtq0wF2DoTkgew7tOT5EwLMk6',
    'RECAPTCHA3_SECRET' => '6LdBtpMiAAAAAD9cxtyxPR2MrJjOzxS7vuDOL4rN',
);
